#!/usr/bin/env php

<?php
require('vendor/autoload.php');


use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

$app = new Application('Task App', '1.0');

$app->register('hello')
    ->setDescription('Offfer a Greeting for name')
    ->addArgument('name', InputArgument::OPTIONAL,'Your Name') // InputArgument::REQUIRED or OPTIONAL
    ->setCode(function(InputInterface $input,OutputInterface $output){
        $name = $input->getArgument('name');
        $output->writeln('<comment>Helo World - '.$name.'</comment>'); //<info> ,
    });



$app->run();